"""
scripts/build_standalone.py
--------------------------------------------------------------------------
PURPOSE
    Build a SINGLE-FILE version of the web app (index.html) in which every
    stylesheet and script is inlined.

WHY
    Two real uses:
      1. Offline / air-gapped demo. The result needs no server, no build step
         and no network of any kind -- it opens with a double-click.
      2. Browser previews that block relative sub-resources. The in-app file
         preview renders HTML inside a sandboxed frame without network access,
         so a multi-file page loses its CSS and JavaScript. The inlined build
         works because everything lives in one document.

USAGE
    python scripts/build_standalone.py

OUTPUT
    ../Password-Strength-Analyzer-standalone.html  (project root)
"""

from __future__ import annotations

import pathlib
import re
import sys

PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
FRONTEND = PROJECT_ROOT / "frontend"
OUTPUT = PROJECT_ROOT / "Password-Strength-Analyzer-standalone.html"

# Inlined in this exact order: data -> engine -> charts -> hashing demo -> app.
SCRIPT_ORDER = [
    "js/data/common_passwords.js",
    "js/data/keyboard_patterns.js",
    "js/data/common_phrases.js",
    "js/data/passphrase_words.js",
    "js/engine.js",
    "js/charts.js",
    "js/hashdemo.js",
    "js/app.js",
]


def read(relative_path: str) -> str:
    return (FRONTEND / relative_path).read_text(encoding="utf-8")


def main() -> int:
    html = read("index.html")
    css = read("css/styles.css")

    # 1. Inline the stylesheet, replacing the <link> tag.
    link_pattern = re.compile(
        r'<link[^>]*rel=["\']stylesheet["\'][^>]*>', re.IGNORECASE)
    if not link_pattern.search(html):
        print("ERROR: no stylesheet link found in frontend/index.html")
        return 1
    html = link_pattern.sub(
        "<style>\n/* ==== inlined from frontend/css/styles.css ==== */\n"
        + css + "\n</style>",
        html, count=1)

    # 2. Inline every local <script src="..."> in dependency order.
    def inline_script(relative_path: str) -> str:
        body = read(relative_path)
        return ("<script>\n/* ==== inlined from frontend/"
                + relative_path + " ==== */\n" + body + "\n</script>")

    for relative_path in SCRIPT_ORDER:
        pattern = re.compile(
            r'<script[^>]*src=["\'][^"\']*' + re.escape(pathlib.Path(relative_path).name)
            + r'["\'][^>]*>\s*</script>', re.IGNORECASE)
        if not pattern.search(html):
            print(f"ERROR: script tag for {relative_path} not found in index.html")
            return 1
        html = pattern.sub(lambda _m, p=relative_path: inline_script(p), html, count=1)

    # 3. Any remote URL left in the document would break offline use.
    remote = re.findall(r'(?:src|href)=["\'](https?://[^"\']+)["\']', html)
    if remote:
        print("ERROR: remote resources remain: " + ", ".join(sorted(set(remote))))
        return 1

    # 4. Add a build notice to the <head> so nobody edits the artifact by hand.
    notice = (
        "<!--\n"
        "  Password Strength Analyzer & Security Suggestion Tool\n"
        "  SINGLE-FILE BUILD - generated by scripts/build_standalone.py\n"
        "  Do not edit this file directly: edit frontend/ and rebuild.\n"
        "  Works offline and makes zero network requests.\n"
        "-->\n"
    )
    html = html.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + notice, 1)

    OUTPUT.write_text(html, encoding="utf-8")
    size_kb = OUTPUT.stat().st_size / 1024
    print(f"Inlined {len(SCRIPT_ORDER)} scripts + 1 stylesheet")
    print(f"Wrote {OUTPUT.relative_to(PROJECT_ROOT)} ({size_kb:.0f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
