"""
scripts/build_frontend_data.py
--------------------------------------------------------------------------
PURPOSE
    Generate the browser-side data files used by the GitHub Pages build.

WHY A BUILD STEP?
    The Python engine reads plain text files in `data/`. A static site cannot
    read those, so this script converts them into small JavaScript modules.
    Running it keeps one single source of truth: `data/*.txt`.

USAGE
    python scripts/build_frontend_data.py
--------------------------------------------------------------------------
"""

from __future__ import annotations

import json
import pathlib

PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
OUT_DIR = PROJECT_ROOT / "frontend" / "js" / "data"


def read_lines(name: str) -> list[str]:
    path = DATA_DIR / name
    lines = []
    if not path.exists():
        return lines
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            lines.append(line)
    return lines


def write_js(filename: str, variable: str, values: list[str], comment: str) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    body = (
        f"// {comment}\n"
        f"// AUTO-GENERATED by scripts/build_frontend_data.py -- do not edit by hand.\n"
        f"// Source: data/{filename.replace('.js', '.txt')}\n"
        f"window.PSA_DATA = window.PSA_DATA || {{}};\n"
        f"window.PSA_DATA.{variable} = {json.dumps(values, ensure_ascii=False)};\n"
        f"if (typeof module !== 'undefined') {{ module.exports = window.PSA_DATA.{variable}; }}\n"
    )
    (OUT_DIR / filename).write_text(body, encoding="utf-8")
    print(f"  wrote frontend/js/data/{filename}  ({len(values)} entries)")


def main() -> None:
    print("Building browser-side data files from data/*.txt ...")
    write_js("common_passwords.js", "commonPasswords",
             read_lines("common_passwords.txt"),
             "Educational common-password list (pattern strings only, no personal data).")
    write_js("keyboard_patterns.js", "keyboardPatterns",
             read_lines("keyboard_patterns.txt"),
             "Curated keyboard-walk fragments used by the pattern detector.")
    write_js("common_phrases.js", "commonPhrases",
             read_lines("common_phrases.txt"),
             "Famous / predictable phrases used to demonstrate why quotes fail as passphrases.")
    write_js("passphrase_words.js", "passphraseWords",
             read_lines("passphrase_words.txt"),
             "Word list for the passphrase generator (Diceware style, local only).")
    print("Done. Commit the generated files so GitHub Pages can serve them.")


if __name__ == "__main__":
    main()
